---
namespace: stdevel
name: uyuni
version: 0.4.5
readme: README.md
authors:
  - Christian Stankowic <info@cstan.io>
description: Collection of modules to manage Uyuni / SUSE Multi-Linux Manager
license:
  - GPL-3.0-only

tags:
  - infrastructure
  - eda
  - linux
  - systemsmanagement
  - uyuni
  - suse
  - manager

dependencies:
  "community.general": "*"
  "containers.podman": "*"
  "ansible.posix": "*"

repository: https://codeberg.org/stdevel/ansible-collection-uyuni
documentation: https://codeberg.org/stdevel/ansible-collection-uyuni/src/branch/main/README.md
homepage: https://codeberg.org/stdevel/ansible-collection-uyuni
issues: https://codeberg.org/stdevel/ansible-collection-uyuni/issues
