---
name: Sanity checks

# concurrency:
#  group: ${{ github.head_ref || github.run_id }}
#  cancel-in-progress: true

on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '0 6 * * *'

jobs:
  sanity-py313-ansible-220:
    runs-on: homelab
    container:
      image: node:26-trixie
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
      - run: apt-get update ; apt-get install -y python3-pip ; pip3 install --user --break-system-packages tox-ansible
      - run: /root/.local/bin/tox -e sanity-py3.13-2.20 --ansible
