---
- name: Ensure having proper architecture
  ansible.builtin.fail:
    msg: "Uyuni only supports x86_64 and aarch64 for openSUSE"
  when:
    - ansible_facts['architecture'] not in ['x86_64', 'aarch64']
