---
- name: Install packages
  ansible.builtin.package:
    name: "{{ proxy_pkgs }}"
  notify: Reboot system (if immutable)
  become: true

- name: Ensure that Podman volumes work as expected
  containers.podman.podman_volume:
    name: test_volume
  become: true

- name: Download air-gapped container image
  community.general.zypper:
    name: suse-multi-linux-manager-{{ proxy_suma_release }}-{{ ansible_facts['architecture'] }}-proxy-image
  notify: Reboot system (if immutable)
  when: proxy_suma_airgapped
  become: true

- name: Enable netavark workaround
  community.general.ini_file:
    path: /etc/systemd/system/uyuni-proxy-pod.service.d/netavark.conf
    owner: root
    group: root
    mode: '0640'
    section: Service
    option: Environment
    value: NETAVARK_FW=iptables
    no_extra_spaces: true
    backup: true
  when: ansible_facts['distribution'] | lower in ['opensuse microos', 'opensuse tumbleweed']
  become: true

- name: Trigger reboot (if necessary)
  ansible.builtin.meta: flush_handlers

- name: Gather current mount facts
  ansible.builtin.mount_facts:
    sources:
      - dynamic

- name: Prepare storage for volumes and database
  ansible.builtin.command:
    cmd: "mgr-storage-proxy {{ proxy_disk }}"
  when:
    - proxy_disk is defined
    - ansible_facts["mount_points"]["/var/lib/containers/storage/volumes"] is not defined
  become: true

- name: Run installation
  ansible.builtin.command: "mgrpxy install podman {{ proxy_config_file }}"
  args:
    creates: /var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/_data
  become: true
