---
- name: Check system registration
  ansible.builtin.command: SUSEConnect --status
  changed_when: false
  register: proxy_scc_registration
  when: proxy_scc_check_registration or proxy_scc_check_modules
  become: true

- name: Register system
  ansible.builtin.command: "suseconnect --url {{ proxy_scc_url }} -r {{ proxy_scc_reg_code_os | upper }} -e {{ proxy_scc_mail }}"
  when:
    - proxy_scc_check_registration | bool
    - proxy_scc_reg_code_os is defined
    - 'proxy_scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    query_filter: "[?identifier == 'SLES'].status"
  become: true

- name: Enable modules
  ansible.builtin.command: "suseconnect --url {{ proxy_scc_url }} -p {{ item.identifier }}"
  loop: "{{ proxy_suma_modules }}"
  when:
    - proxy_scc_check_modules | bool
    - 'proxy_scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    query_filter: "[?identifier == '{{ item.name }}'].status"
  become: true

- name: Register MLM
  ansible.builtin.command: "suseconnect --url {{ proxy_scc_url }} -p Multi-Linux-Manager-Proxy-SLE/{{ proxy_suma_release }}/{{ ansible_facts['architecture'] }} -r {{ proxy_scc_reg_code_mlm | upper }} -e {{ proxy_scc_mail }}"
  when:
    - proxy_scc_check_registration | bool
    - 'proxy_scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    query_filter: "[?identifier == 'Multi-Linux-Manager-Proxy'].status"
  become: true
