---
- name: Converge machines
  hosts: all
  become: true
  pre_tasks:
    - name: Fix FQDN
      ansible.builtin.set_fact:
        ansible_fqdn: almalinux-proxy.podman.loc

  roles:
    - role: stdevel.uyuni.proxy
      proxy_allow_unsupported_distributions: true
      proxy_config_file: /root/foo.bar
