---
- name: Converge machines
  hosts: all
  become: true
  roles:
    - role: uyuni_project.uyuni.server
      server_allow_unsupported_distributions: true
      server_enable_monitoring: true
      # server_channels:
      #   - name: almalinux9
      #     arch: x86_64
      #   - name: almalinux9-appstream
      #     arch: x86_64
      #   - name: almalinux9-uyuni-client
      #     arch: x86_64
      # # server_release: '2023.03'
