---
proxy_requirements:
  - podman
  - parted
  - xfsprogs
  - rsync

proxy_pkgs:
  - mgrpxy
  - uyuni-storage-setup-proxy
  - netavark

proxy_repos:
  - url: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/Debian_13
    name: systemsmanagement_Uyuni_Stable_ContainerUtils
    gpg: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/Debian_13/Release.key
    suites: ./
