---
proxy_requirements:
  - podman

proxy_pkgs:
  - mgrpxy
  - mgrpxy-bash-completion

proxy_suma_modules:
  - name: "Containers Module 15 SP7 x86_64"
    identifier: "sle-module-containers/15.7/{{ ansible_facts['architecture'] }}"
    search: "sle-module-containers"
