---
# check requirements
proxy_allow_unsupported_distributions: false
proxy_check_requirements: true

# required core packages
proxy_core_packages:
  - man
  - firewalld

# SCC settings
proxy_scc_url: https://scc.suse.com
proxy_scc_check_registration: true
proxy_scc_check_modules: true

# SUSE MLM-related settings
proxy_suma_release: 5.1
proxy_suma_airgapped: false
