---
server_requirements:
  - podman

server_pkgs:
  - mgradm
  - mgrctl
  - mgradm-bash-completion
  - mgrctl-bash-completion
  - netavark

server_suma_modules:
  - name: "Containers Module 15 SP7 x86_64"
    identifier: "sle-module-containers/15.7/{{ ansible_facts['architecture'] }}"
    search: "sle-module-containers"
