---
server_requirements:
  - podman
  - parted
  - xfsprogs
  - rsync

server_pkgs:
  - mgradm
  - mgrctl
  - netavark
  - uyuni-storage-setup-server

server_repos:
  - url: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/Ubuntu_24.04
    name: systemsmanagement_Uyuni_Stable_ContainerUtils
    gpg: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/Ubuntu_24.04/Release.key
    suites: ./
