---
- name: Converge machines
  hosts: all
  become: true
  pre_tasks:
    - name: Fix FQDN
      ansible.builtin.hostname:
        name: uyuni-proxy.podman.loc

  roles:
    - role: uyuni_project.uyuni.proxy
      proxy_config_file: /root/foo.bar
