---
- name: Ensure having proper architecture
  ansible.builtin.fail:
    msg: "SUSE MLM only supports x86_64, aarch64, ppc64l and s390x for SLE/SL Micro"
  when:
    - ansible_facts['architecture'] not in ['x86_64', 'aarch64', 'ppc64l', 's390x']

- name: Ensure having SUSE MLM release equal/greater than 5.1
  ansible.builtin.fail:
    msg: "SUSE MLM releases older than 5.1 are unsupported - use an older version of this collection"
  when:
    - server_suma_release is defined
    - "server_suma_release is version('5.1', '<')"

- name: Ensure having supported SL Micro release for SUSE MLM 5.2
  ansible.builtin.fail:
    msg: "Please upgrade to SL Micro 6.2"
  when:
    - server_suma_release == 5.2
    - ansible_facts['distribution_version'] != '6.2'


- name: Ensure having supported SL Micro release for SUSE MLM 5.1
  ansible.builtin.fail:
    msg: "Please upgrade to SL Micro 6.1"
  when:
    - server_suma_release == 5.1
    - ansible_facts['distribution_version'] != '6.1'
