---
- name: Install requirements (Debian-like)
  ansible.builtin.apt:
    name: "{{ server_requirements }}"
    update_cache: true
  when: ansible_facts['os_family'] | lower == "debian"
  become: true

- name: Install requirements
  ansible.builtin.package:
    name: "{{ server_requirements }}"
  when: ansible_facts['os_family'] | lower != "debian"
  become: true
